### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cassio299** [Olen/home-assistant-openplantbook#1]
The integration is set up using the GUI what do you mean???? Im in yaml mode does that mean that I can't set op openplantbook ??? I can't find anywhere to put in my credentials created on the open plant home page

**Comment by Olen** [comment]
You go to Settings -> Integrations in HA, click add integration, find Openplantbook and add your credentials there.

**Comment by cassio299** [comment]
Thank you that saved me from my panic attack and thank your for the plant integration
