### ISSUE TITLE
Stuck on "Please wait, starting configuration wizard for openplantbook"

### ISSUE THREAD

**Issue by AnderssonPeter** [Olen/home-assistant-openplantbook#14]
Hi I successfully installed the addon using hacs, but when I try the add the integration it just gets stuck on `Please wait, starting configuration wizard for openplantbook`, if I open network in the developer tools, it just stuck loading `https://homeassistant.server.com/api/config/config_entries/flow` and nothing is logged in the console output or homeassistant logs.

I'm not 100% sure if this is the same issue as #13.

**Comment by slaxor505** [comment]
Hi! Apologies, this is curly fingers issue. I've just corrected the type and submitted a new PR. 
https://github.com/Olen/home-assistant-openplantbook/pull/15
@Olen Please approve.

**Comment by slaxor505** [comment]
I bet it is the same issue so let's see if the beta2 patch will fix it. I've just tested this scenario and it seems ok to me. If it won't fix the error can you please enable DEBUG logging for the integration and recheck and see if it tells you anything in logs.

**Comment by Olen** [comment]
If you use the beta-version, it might be the same issue.
New beta released now.

If you don't use the beta version, please try the latest beta and see if it fixes the problem.

**Comment by AnderssonPeter** [comment]
@Olen it works great now, thanks quick fix!!
