### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by coxtor** [Olen/home-assistant-openplantbook#16]
When trying to add my credentials I get the following error:

I am using docker-compose with traefik. So far everything else is working fine also public tls with multiple devices. Adittionally the Plant integration ( I have configured 34 Sensors manually) are working fine.

It would be good to be able to disable ssl_verify in the sdk perhaps?

```
2024-01-26 18:06:33.553 ERROR (MainThread) [openplantbook_sdk.sdk] Cannot connect to host open.plantbook.io:443 ssl:True [SSLCertVerificationError: (5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
homeassistant     | 2024-01-26 18:06:33.553 ERROR (MainThread) [custom_components.openplantbook.config_flow] Unable to connect to OpenPlantbook: Cannot connect to host open.plantbook.io:443 ssl:True [SSLCertVerificationError: (5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
```

**Comment by Olen** [comment]
@slaxor505 Do you have a certificate issue?

**Comment by slaxor505** [comment]
No, I don't. We've discussed this issue with the person already in Discord.
I don't think that disabling TLS validation is a good idea. This seems to
be one off occurrence of the issue. It's likely intermediate proxy or
outdated encryption algorithms on the host. I'll continue troubleshooting
in Discord.
