### ISSUE TITLE
Error while adding Integration

### ISSUE THREAD

**Issue by LotharMadsson** [Olen/home-assistant-openplantbook#19]
Followed all the steps but I get the following error when I try to add the integration via the **Devices & Integrations** panel:
`Config flow could not be loaded: {"message":"Invalid handler specified"}`

**Comment by Olen** [comment]
Please add some more information. Logs, versions etc.

**Comment by LotharMadsson** [comment]
Following HA log is provided
`2024-03-04 21:16:38.277 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration openplantbook: cannot import name 'ServiceResponse' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)`
Using Home Assistant **2023.4.6**

**Comment by Olen** [comment]
The latest versions of the integration requires a newer version of HA.

Please upgrade HA and try again, or select an older version of the integration.

**Comment by LotharMadsson** [comment]
Upgrading Home Assistant resolved the issue! Thanks for pointing it out!
