### ISSUE TITLE
Doesn't have upload button

### ISSUE THREAD

**Issue by Balooforever** [Olen/home-assistant-openplantbook#22]
Hi,

I love your add-on !

I still have a small question: why don't I have the buttons to send my data to openplantbook? I only have the button to download the image.

Is this linked to the deactivation of the cloud in the HA config?

Thank you very much for your work

**Comment by Olen** [comment]
There is no built in upload-button.

You can create a button (or automation, or whatever you like) that triggers the service call:
https://github.com/Olen/home-assistant-openplantbook?tab=readme-ov-file#openplantbookupload

**Comment by Balooforever** [comment]
Hi @Olen 

Thank for your reply, my question is about this options : 

On the readme : 
![](https://github.com/Olen/home-assistant-openplantbook/blob/main/images/config-options.png)

On my config : 
![image](https://github.com/Olen/home-assistant-openplantbook/assets/48917118/d7c6b237-cbfa-4157-92c1-e03feb5e2816)

It's "normal" ?

Thank you :)

**Comment by slaxor505** [comment]
Hi mate,You need to be on beta version to have upload sensor data functionality. Slava
-------- Original message --------From: Balooforever ***@***.***> Date: 26/4/24  16:43  (GMT+10:00) To: Olen/home-assistant-openplantbook ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [Olen/home-assistant-openplantbook] Doesn't have upload button (Issue #22) 
Hi @Olen
Thank for your reply, my question is about this options :
On the readme :

On my config :
image.png (view on web)
It's "normal" ?
Thank you :)

**Comment by slaxor505** [comment]
This is not a button in the component config but a hass service. You can find it in HASS services tab. Do you know how to find it?
-------- Original message --------From: Olen ***@***.***> Date: 25/4/24  21:35  (GMT+10:00) To: Olen/home-assistant-openplantbook ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [Olen/home-assistant-openplantbook] Doesn't have upload button (Issue #22) 
There is no built in upload-button.
You can create a button (or automation, or whatever you like) that triggers the service call:
https://github.com/Olen/home-assistant-openplantbook?tab=readme-ov-file#openplantbookupload

**Comment by Balooforever** [comment]
> Hi mate,You need to be on beta version to have upload sensor data functionality. Slava -------- Original message --------From: Balooforever ***@***.***> Date: 26/4/24 16:43 (GMT+10:00) To: Olen/home-assistant-openplantbook ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [Olen/home-assistant-openplantbook] Doesn't have upload button (Issue #22) Hi @Olen Thank for your reply, my question is about this options : On the readme : On my config : image.png (view on web) It's "normal" ? Thank you :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thanks for the information, I didn't know it was in the beta version.

Yes, no problem with the service, I was just surprised not to have the same screen.
