### ISSUE TITLE
OpenPlantBook to UI

### ISSUE THREAD

**Issue by MarcelS1988** [Olen/home-assistant-openplantbook#3]
Hello Olen,

I like intergration, but how to set up the following:
![image](https://user-images.githubusercontent.com/30636298/210443945-25b0f65f-3394-4737-bfd9-566c802a544d.png)

Hope you have a example.

Thanks

**Comment by AverageJoe89** [comment]
"This UI is not part of the integration. It is just an example of how to use the service calls."

**Comment by Olen** [comment]
I just created this:
https://github.com/Olen/home-assistant-openplantbook/blob/main/examples/GUI.md

There might be some missing details, but it should get you most of the way, I think.

**Comment by MarcelS1988** [comment]
@Olen Thank you!!!!
