### ISSUE TITLE
Invalid download path in HAOS

### ISSUE THREAD

**Issue by zatricky** [Olen/home-assistant-openplantbook#4]
Is there a path that *should* be used for an HAOS-based install? The default and suggested paths all seem to give the error "Invalid download path" :-(

**Comment by Olen** [comment]
I'm sorry I don't know the file structure of HAOS.
You can probably find information about that in the documentation.  
Also, you need to make sure you create any subdirectories you want to download the images to before you set it up.

**Comment by Raptime** [comment]
I know this is closed but I ran into this issue and fixed it this way:
1. log into haos
2. create the missing folder: `mkdir -p /mnt/data/supervisor/homeassistant/www/images/plants`
3. in the integration use the following path: `/config/www/images/plants/`
