### ISSUE TITLE
Path to image

### ISSUE THREAD

**Issue by WebfinityDesign** [Olen/home-assistant-openplantbook#5]
First a big compliment for the new plant integration and the Openplantbook! I installed them both an d also the custom lovelace card and it works very well! Nice job!

I also copied your example to query the database from HA. This works also very well, but of course, I didnt't read the installation notes very well and installed it with an path to the images that didn't exist yet. So now all is working but I don't have the pictures from Openplantbook. Is there a way to correct this? Is there a file I can edit?

Thanks, and keep up the good work!

**Comment by Olen** [comment]
If you find the plants under Settings and click "Configure", you have a checkmark to "Force refresh from openplantbook"
That should download the images again.  Make sure the path exists before you do this.
