### ISSUE TITLE
Error when setting up V1.2.0: Config flow could not be loaded

### ISSUE THREAD

**Issue by Slalamander** [Olen/home-assistant-openplantbook#9]
When the integration version v1.2.0 is setup during startup, it runs into an error. When trying to reconfigure it, I get an error message saying: _Config flow could not be loaded: {"message":"Invalid handler specified"}_.
This also happened after removing and redownloading the integration. However, when using V1.1.0, it does not.

My logs show the following message for the setup error:
`Setup failed for custom integration openplantbook: Unable to import component: cannot import name 'ServiceResponse' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)`

**Comment by Olen** [comment]
What version of HA are you running?
1.2.0 requires 2023.7 or higher, I believe.

**Comment by Slalamander** [comment]
I was on 2023.6. Updating did indeed solve the issue!
